services:
    convos:
      image: 'ghcr.io/convos-chat/convos:stable'
      container_name: 'convos'
      restart: unless-stopped
      volumes:
        - './convos:/data'
      networks:
        - traefik
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.convos.rule=Host(`convos.${BASE_DOMAIN:-ozeliurs.com}`)'
        - 'traefik.http.routers.convos.entrypoints=websecure'
        - 'traefik.http.routers.convos.tls=true'
        - 'traefik.http.routers.convos.tls.certresolver=cloudflare'
        - 'traefik.http.services.convos.loadbalancer.server.port=3000'

networks:
  traefik:
    external: true